blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Dokumentation
    url: https://github.com/phkoenig/kessel-boilerplate/tree/main/docs
    about: Schau zuerst in die Dokumentation, vielleicht findest du dort eine LÃ¶sung.
  - name: ðŸ’¬ Diskussionen
    url: https://github.com/phkoenig/kessel-boilerplate/discussions
    about: FÃ¼r allgemeine Fragen und Diskussionen.
